Add some features to rc/hdcompile and control/service

diff --git a/control/service b/control/service
--- a/control/service
+++ b/control/service
@@ -8,9 +8,10 @@ require_root(){
 
 get_service_status(){
 	[[ -e "/run/service/$1" ]] || { echo -e "[ \e[1;34mdisabled\e[0m ] $1"; return; }
+	[[ -e "/run/service/$1/stopped" ]] && { echo -e "[ \e[1;33mstopped\e[0m  ] $1"; return; }
 	local status="$(cat /run/service/$1/status)"
 	case $status in
-		run*)		echo -e "[ \e[1;32mrunnning\e[0m ] $1";;
+		run*)		echo -e "[ \e[1;32mrunning\e[0m ] $1";;
 		exited=0*)	echo -e "[  \e[1;32mexited\e[0m  ] $1";;
 		kill*)		echo -e "[  \e[1;31mkilled\e[0m  ] $1";;
 		stop*)		echo -e "[ \e[1;33mstopped\e[0m  ] $1";;
@@ -23,6 +24,9 @@ case $1 in
 		{
 			for service in $(ls -1 /etc/init.d)
 			do
+				case $service in
+					stop_*|sendsignals|halt|reboot) continue;;
+				esac
 				get_service_status $service
 			done
 			unset service
@@ -30,26 +34,28 @@ case $1 in
 	start)
 		require_root
 		pushd /etc/rc.d &>/dev/null
-			make -s $2 -j
+			make -s $2 -j && {
+				rm -f /run/service/$2/stopped &>/dev/null
+			}
 		popd &>/dev/null;;
 	stop)
 		require_root
 		[[ -e /etc/init.d/stop_$2 ]] && {
 			/etc/init.d/stop_$2 && \
 				{ msg_ok "Stopped $2" 
-					echo "stopped     " > /run/service/$2/status	
+					touch /run/service/$2/stopped	
 				} || \
 				msg_fail "Failed to stop $2"
 			exit 0;
 		}
 		pid="$(cat /run/service/$2/supervisor)"
 		kill -15 $pid &>/dev/null || echo "service: unable to kill"
-		echo "stopped      " > /run/service/$2/status
+		touch /run/service/$2/stopped
 		;;
 	reload)
 		require_root
 		pid="$(cat /run/service/$2/supervisor)"
-		kill -1 $pid || echo "service: unable to reload"
+		kill -HUP $pid || echo "service: unable to reload"
 		;;
 	restart)
 		$0 stop $2 && $0 start $2;;
@@ -59,6 +65,7 @@ case $1 in
 		echo "$(cat /run/service/$2/pid)";;
 	is-running)
 		[[ -e "/run/service/$2" ]] || { exit 1; }
+		[[ -e "/run/service/$2/stopped" ]] && exit 1
 		status="$(cat /run/service/$2/status)"
 		case $status in
 			run*)		exit 0;;
@@ -67,6 +74,64 @@ case $1 in
 			*)		exit 1;;
 		esac
 		;;
+	rc-recompile)
+		require_root
+		cd /etc/rc.d
+		hdcompile init.d > Makefile
+		;;
+	enable)
+		require_root
+		service="$2"
+		runlevel="$3"
+		{ [[ -z "$service" ]] || [[ -z "$runlevel" ]]; } && \
+			echo "Usage: ${0##*/} enable <service> <0-6,S>" && exit 1
+		[[ -e "/etc/init.d/$service" ]] || \
+			echo "$service: no such service" && exit 1
+		case $runlevel in
+			[0-6]|S) true;;
+			*) echo "Usage: ${0##*/} enable <service> <0-6,S>" && exit 1;;
+		esac
+		grep -q $service /etc/rc.d/$runlevel/depends && \
+			echo "$service: already enabled" && exit 1
+		echo $service >> /etc/rc.d/$runlevel/depends
+		$0 rc-recompile
+		;;
+	disable)
+		require_root
+		service="$2"
+		runlevel="$3"
+		{ [[ -z "$service" ]] || [[ -z "$runlevel" ]]; } && \
+			echo "Usage: ${0##*/} disable <service> <0-6,S>" && exit 1
+		[[ -e "/etc/init.d/$service" ]] || \
+			echo "$service: no such service" && exit 1
+		case $runlevel in
+			[0-6]|S) true;;
+			*) echo "Usage: ${0##*/} disable <service> <0-6,S>" && exit 1;;
+		esac
+		grep -q $service /etc/rc.d/$runlevel/depends || \
+			echo "$service: already disabled" && exit 1
+		sed -i "/$service/d" /etc/rc.d/$runlevel/depends
+		$0 rc-recompile
+		;;
 esac
 
 exit	
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
